name: Adam Hammes
description: Adam Hammes' Website
author: Adam Hammes
url: http://hammes.io
permalink: /:categories/:title/
excerpt_separator: <!--more-->
source: site/
sass:
  sass_dir: assets/_scss
  style: compressed

markdown: kramdown
